# 形式化架构理论统一项目配置文件
# Formal Architecture Theory Integration Project Configuration

# 项目基本信息
project:
  name: "形式化架构理论统一项目"
  version: "1.0.0"
  description: "构建统一的形式化架构理论体系，实现从哲学基础到实践应用的完整链条"
  author: "FormalUnified Team"
  created_date: "2024-12-16"

# 理论体系配置
theory_systems:
  - name: "01-哲学基础理论"
    path: "FormalUnified/01-哲学基础理论"
    weight: 1.0
    dependencies: []
    
  - name: "02-数学理论体系"
    path: "FormalUnified/02-数学理论体系"
    weight: 1.0
    dependencies: ["01-哲学基础理论"]
    
  - name: "03-形式语言理论体系"
    path: "FormalUnified/03-形式语言理论体系"
    weight: 1.0
    dependencies: ["01-哲学基础理论", "02-数学理论体系"]
    
  - name: "04-形式模型理论体系"
    path: "FormalUnified/04-形式模型理论体系"
    weight: 1.0
    dependencies: ["02-数学理论体系", "03-形式语言理论体系"]
    
  - name: "05-编程语言理论体系"
    path: "FormalUnified/05-编程语言理论体系"
    weight: 1.0
    dependencies: ["03-形式语言理论体系", "04-形式模型理论体系"]
    
  - name: "06-软件架构理论体系"
    path: "FormalUnified/06-软件架构理论体系"
    weight: 1.0
    dependencies: ["04-形式模型理论体系", "05-编程语言理论体系"]
    
  - name: "07-分布式与微服务"
    path: "FormalUnified/07-分布式与微服务"
    weight: 1.0
    dependencies: ["04-形式模型理论体系", "06-软件架构理论体系"]
    
  - name: "08-实践与应用"
    path: "FormalUnified/08-实践与应用"
    weight: 1.0
    dependencies: ["05-编程语言理论体系", "06-软件架构理论体系", "07-分布式与微服务"]
    
  - name: "09-索引与导航"
    path: "FormalUnified/09-索引与导航"
    weight: 0.8
    dependencies: ["01-哲学基础理论", "02-数学理论体系", "03-形式语言理论体系", 
                   "04-形式模型理论体系", "05-编程语言理论体系", "06-软件架构理论体系",
                   "07-分布式与微服务", "08-实践与应用"]

# AI建模引擎配置
ai_modeling_engine:
  enabled: true
  model_type: "enhanced"
  verification_levels:
    - "syntax"
    - "semantics"
    - "constraint_verification"
    - "architecture_compliance"
    - "security_check"
    - "performance_analysis"
  
  output_formats:
    - "python"
    - "rust"
    - "go"
    - "typescript"
    - "java"
    - "csharp"
  
  pattern_generation:
    enabled: true
    max_patterns: 100
    min_confidence: 0.7
  
  code_generation:
    enabled: true
    include_tests: true
    include_documentation: true
    code_quality_threshold: 0.8

# 跨理论验证引擎配置
cross_theory_verification:
  enabled: true
  verification_types:
    - "internal_consistency"
    - "external_consistency"
    - "cross_mapping"
    - "dependency_analysis"
  
  thresholds:
    min_completeness: 0.7
    min_consistency: 0.8
    min_integration: 0.5
    min_confidence: 0.7
  
  analysis_depth:
    max_dependency_depth: 5
    max_concept_analysis: 1000
    max_mapping_analysis: 100

# 理论到实践映射配置
theory_to_practice_mapping:
  enabled: true
  supported_languages:
    - "rust"
    - "go"
    - "python"
    - "typescript"
    - "java"
    - "csharp"
  
  mapping_rules:
    - pattern: "state_machine"
      rust_template: "state_machine_rust.template"
      go_template: "state_machine_go.template"
      python_template: "state_machine_python.template"
    
    - pattern: "petri_net"
      rust_template: "petri_net_rust.template"
      go_template: "petri_net_go.template"
      python_template: "petri_net_python.template"
    
    - pattern: "temporal_logic"
      rust_template: "temporal_logic_rust.template"
      go_template: "temporal_logic_go.template"
      python_template: "temporal_logic_python.template"
  
  validation:
    enabled: true
    syntax_check: true
    semantic_check: true
    constraint_check: true

# 输出配置
output:
  base_directory: "output"
  formats:
    - "json"
    - "yaml"
    - "markdown"
    - "html"
  
  visualization:
    enabled: true
    formats:
      - "png"
      - "svg"
      - "pdf"
    graph_layout: "hierarchical"
    color_scheme: "theory_based"

# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "formal_unified.log"
  max_size: "10MB"
  backup_count: 5

# 性能配置
performance:
  max_concurrent_analysis: 4
  max_file_size: "100MB"
  cache_enabled: true
  cache_size: "1GB"
  timeout_seconds: 300

# 安全配置
security:
  input_validation: true
  output_sanitization: true
  max_recursion_depth: 10
  allowed_file_types: ["md", "py", "rs", "go", "ts", "java", "cs"]

# 开发模式配置
development:
  debug_mode: false
  verbose_output: false
  save_intermediate_results: true
  auto_backup: true
  backup_interval_hours: 24 